paths:
  /recipes/{recipeId}:
    get:
      x-amazon-apigateway-integration:
        type: "aws"
        httpMethod: "GET"
        uri: "arn:aws:apigateway:eu-central-1:lambda:path/2015-03-31/functions/FreakyLambdaArn/invocations"
        responses:
          default:
            statusCode: "200"
        passthroughBehavior: "when_no_match"
        contentHandling: "CONVERT_TO_TEXT"
    put:
      x-amazon-apigateway-integration:
        type: "aws"
        httpMethod: "PUT"
        uri: "arn:aws:apigateway:eu-central-1:lambda:path/2015-03-31/functions/FreakyLambdaArn/invocations"
        responses:
          default:
            statusCode: "200"
        passthroughBehavior: "when_no_match"
        contentHandling: "CONVERT_TO_TEXT"
    delete:
      x-amazon-apigateway-integration:
        type: "aws"
        httpMethod: "DELETE"
        uri: "arn:aws:apigateway:eu-central-1:lambda:path/2015-03-31/functions/FreakyLambdaArn/invocations"
        responses:
          default:
            statusCode: "200"
        passthroughBehavior: "when_no_match"
        contentHandling: "CONVERT_TO_TEXT"
  /recipes:
    get:
      x-amazon-apigateway-integration:
        type: "aws"
        httpMethod: "GET"
        uri: "arn:aws:apigateway:eu-central-1:lambda:path/2015-03-31/functions/FreakyLambdaArn/invocations"
        responses:
          default:
            statusCode: "200"
        passthroughBehavior: "when_no_match"
        contentHandling: "CONVERT_TO_TEXT"
    post:
      x-amazon-apigateway-integration:
        type: "aws"
        httpMethod: "POST"
        uri: "arn:aws:apigateway:eu-central-1:lambda:path/2015-03-31/functions/FreakyLambdaArn/invocations"
        responses:
          default:
            statusCode: "200"
        passthroughBehavior: "when_no_match"
        contentHandling: "CONVERT_TO_TEXT"