name: Deploy Backend

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Deploy backend
      uses: youyo/aws-cdk-github-actions@v2
      with:
        working_dir: 'infrastructure'
        cdk_subcommand: 'deploy'
        cdk_stack: 'Backend-InfrastructureStack'
        cdk_args: '--require-approval never'
        actions_comment: false
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}